

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  
  
- name: Build and push Docker images
  uses: docker/build-push-action@v3.2.0

      with:
        image: jasek777/websvrtesting
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
