name:docker build and push ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  
  - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: nanajanashia/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
